### ISSUE TITLE
Freevo metadata file (FXD) records duration in seconds

### ISSUE THREAD

**Issue by srowles** [get-iplayer/get_iplayer#111]
The metadata info written out to the .fxd file which freevo uses records the duration as the number of seconds. The Freevo UI displays this value as simple text on the screen. This means that you see very odd values (e.g. 3600 instead of 60 minutes) and it's not ideal having to divide by 60 all the time in my head to work out how long things are.

I've hacked my local version by adding a new line after 4829:

$self->{duration} = $self->{duration} / 60;

Which is clearly not the right fix but works for me for now, ideally this would provide a better format of text, e.g. 1 hr, 30 min etc.

**Comment by srowles** [comment]
Been off over Christmas and forgot to check back in. I'll check this evening to see what Freevo does when there is no info about duration.

**Comment by dinkypumpkin** [comment]
Thanks, but it's only a matter of curiosity at this point.  The runtime was wrong in Kodi/XBMC metadata files as well, so will be fixed in next release.
