### ISSUE TITLE
Generate correct episode number when episode is split into multiple broadcasts

### ISSUE THREAD

**Issue by dinkypumpkin** [get-iplayer/get_iplayer#112]
From: https://squarepenguin.co.uk/forums/topic/silent-witness-series-18-episode-numbers/

For rare programmes like Silent Witness where episodes are split into multiple parts (e.g., broadcast on two nights in the same week), the normal episode number in metadata refers to all parts, not each broadcast as is usual.

**Comment by bobsthecoder** [comment]
Is there a workaround like you described for Plex? Even if a little messy? Thanks

**Comment by dinkypumpkin** [comment]
My suggestion in the forum thread wasn't specific to Plex

**Comment by bobsthecoder** [comment]
In that case is there a config file to edit or a perl script to change? I can not see any options on the GUI. Or is this only if you use the command line? Thanks

**Comment by dinkypumpkin** [comment]
As I said in the forum thread, the default file prefix is good enough to avoid collisions.  From your question, I presume you don't know how to set a custom file prefix, so I also presume you haven't done so. Thus, you'll get the default output file naming with both CLI and Web PVR.  In other words, just download.

**Comment by bobsthecoder** [comment]
You are spot on, I don't know how to set a custom file prefix and so I haven't done so. Can you tell me how to do that? I use the GUI and PVR on Mac and I can not find anywhere to make those changes. I can not find it in "Preferences". I would prefer to avoid using the command line as I like the PVR function a lot. Yes I can see it is to do with  --fileprefix but where can I change the defaults?

**Comment by dinkypumpkin** [comment]
CLI with --fileprefix is the only option.  Don't conflate get_player with Get iPlayer Automator.  Setting a file prefix for get_player will not affect GiA.  As to how to save settings, see examples page in project wiki.
