### ISSUE TITLE
Downloading an embedded clip doesn't work

### ISSUE THREAD

**Issue by kbavishi** [get-iplayer/get_iplayer#117]
Command is: "get_iplayer --get --proxy http://195.40.6.43:3128 --type=radio --pid p02hhl1t"
Version: 2.90

Here are the logs: 

INFO: Using Proxy http://195.40.6.43:3128
INFO: Clip-only pid detected
INFO: Trying pid: p02hhl1t using type: radio
INFO: Trying to stream pid using type radio
INFO: pid not found in radio cache
Matches:

INFO: 1 Matching Programmes
INFO: 1 Matching Programmes
INFO: Checking existence of default version
INFO: flashaacstd1 modes will be tried for version default
INFO: Trying flashaacstd1 mode to record radio:  -
INFO: File name prefix = Composer_of_the_Week_-_Franz_Joseph_Haydn_1732-1809_Composer_of_the_Week_-_Haydns_time_at_the_Hungarian_palace_of_Eszterhaza_p02hhl1t_default
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: rtmp server sent error
ERROR: rtmp server requested close
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to stream file /Users/karan/Downloads/Composer_of_the_Week_-_Franz_Joseph_Haydn_1732-1809_Composer_of_the_Week_-_Haydns_time_at_the_Hungarian_palace_of_Eszterhaza_p02hhl1t_default.partial.m4a.flv via RTMP
INFO: skipping flashaacstd1 mode
ERROR: Failed to record 'Composer of the Week - Franz Joseph Haydn (1732-1809): Composer of the Week -  Haydn's time at the Hungarian palace of Eszterhaza (p02hhl1t)'

**Comment by dinkypumpkin** [comment]
Cannot reproduce - works fine here.  The most likely reason is that you're blocked because you're outside the UK.  Non-UK access is strictly off-limits here, so I can't help you further.

**Comment by kbavishi** [comment]
Well, actually the radio clip does not need UK access. I can play the embedded clip from my browser http://www.bbc.co.uk/programmes/p02hhl1t

It does throw an error in get_iplayer if I do not use the proxy (something about "outside the UK"). But this error wasn't being displayed, infact I had another tv download going on in parallel without any issues.

I also tried using the --url option without any luck. Am I doing anything obviously wrong?

**Comment by kbavishi** [comment]
I just removed the ```--proxy``` option, and it worked.

**Comment by dinkypumpkin** [comment]
Only low-quality audio is available outside the UK.  You were trying to subvert that by using `--proxy`, but were most likely blocked by the CDN.  It could be something else, but again, you're accessing iPlayer from outside the UK, so I can't help you.

**Comment by dinkypumpkin** [comment]
I should add that the UK and non-UK streams also may be the same audio quality, but have different stream URLs.  `--proxy` would give you UK streams, which may be blocked, as appears to be the case here.
