### ISSUE TITLE
rtmpdump exits with '2' for certain shows.

### ISSUE THREAD

**Issue by pramodhegde** [get-iplayer/get_iplayer#118]
When downloading certain shows rtmpdump started exiting with an exit code of '2' very frequently which kicks get_iplayer to retry. The download progresses for a bit (say few kB's) and then the same pattern reoccurs. After a certain point in time, exit codes become '1' and later get_iplayer gives up. 

If I delete the partial download and attempt it again, it starts behaving the same way, but at a different point in time in the download, so I don't think it's a file corruption at the other end. Has happened to me with multiple shows starting Friday.

```
get_iplayer --modes best --pid b051zzb4
```

**Comment by dinkypumpkin** [comment]
Cannot reproduce - works fine here.  There is no way to know from the above description what is happening on your machine, but I suspect you've run afoul of geo-blocking and/or server errors.  There is nothing get_player can do about either. I'm assuming from your GitHub profile that you are using get_iplayer outside the UK, in which case I can't help you further.

**Comment by dinkypumpkin** [comment]
Also: If you're only trying to download HD programme versions, you may have better luck with lower-quality versions.
