### ISSUE TITLE
Make HLS/MPEG-DASH hybrid default stream format for on-demand audio

### ISSUE THREAD

**Issue by dinkypumpkin** [get-iplayer/get_iplayer#130]
RTMP is current default streaming format for on-demand audio, but BBC have announced plans to drop it in favour of HLS/MPEG-DASH.  get_iplayer already has support for existing HLS streams. However 320k on-demand streams (except R3) are only available via MPEG-DASH.

**Comment by Rich14** [comment]
Where can I get help please for Get_iPlayer.
Ubuntu 12.04 Dell 2400 1GB ram.
Please could someone explain what I have to do to correct Get_iPlayer errors 
and were I could get " avconv " from as instructed in the first error.
Thank you for any help Richard
First Error>>>>>>>>>>>
ffmpeg version 0.8.6-4:0.8.6-0ubuntu0.12.04.1, Copyright (c) 2000-2013 the Libav developers built on Apr 2 2013 17:00:59 with gcc 4.6.3 *** THIS PROGRAM IS DEPRECATED *** This program is only provided for compatibility and will be removed in a future release. Please use avconv instead. [flv @ 0x9984a80] Estimating duration from bitrate, this may be inaccurate 
Second Error:>>>>>>>>>
RTMPDump v2.4 (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL Connecting ... INFO: Connected... ERROR: RTMP_ReadPacket, failed to read RTMP packet header INFO: Command exit code 1 (raw code = 256) WARNING: Failed to stream file /home/richard/Gardeners_World_-_2013_Episode_12_b02w88wy_default.partial.mp4.flv via RTMP INFO: skipping flashhigh1 mode

**Comment by dinkypumpkin** [comment]
Post your query in the forums at squarepenguin.co.uk. Also, have the courtesy to not hijack an issue thread with a completely unrelated post.  You risk having your post deleted without reply.  Your post above will be deleted in 24 hours.

**Comment by dinkypumpkin** [comment]
Closed by 673793ae992a5e02d1726ce0216f27cbe924a21a
