### ISSUE TITLE
Logic errors affecting first run on new install, or --pluginsupdate use

### ISSUE THREAD

**Issue by JNicoll** [get-iplayer/get_iplayer#132]
v2.91, on a Windows XP system.

The error message:

ERROR: <perlscriptname> is not writable - aborting update (maybe a package manager was used to install get_iplayer?)

which I just received (under Windows XP) was discussed recently in a mail list thread starting:

Message-ID: <54D8FF57.7020803@errichel.co.uk>
Date: Mon, 09 Feb 2015 18:41:27 +0000
Subject: New Linux Installation Question

where everybody assumed it was caused by a permissions issue on a linux system, but I think there's a bigger problem...

I was doing a planned install (late, I know) of v2.91, on a system where v2.90 is in regular use.  The new v2.91 code is deliberately not being installed where the older version lives as I want 2.90 to continue to run while I play with 2.91.

I temporarily sidelined the default profile folder used by my real v2.90 install and tried to run the new 2.91 as if it was being installed for the first time.  I expected it to create a new default profile folder then populate it with the current plugins definitions & then create a new tv.cache file within.  (Because of cache file format changes between 2.90 and 2.91 I need to contemplate the effects those changes will have on my other cache file processing programmes.) 

It just so happens that I keep all my copies (with varying levels of customisation) of the get_iplayer perl program with the read-only file attribute set (because that influences how my text-editor treats such a file and in particular its embedded tab characters).    So, this is what happened:

C:\>"C:\My Dropbox\CLIpgms\get_iplayer_2-91_002_notrspcs.pl"
get_iplayer v2.91, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.

WARNING: Running the updater again to obtain plugins.
ERROR: C:\My Dropbox\CLIpgms\get_iplayer_2-91_002_notrspcs.pl is not writable - aborting update (maybe a package manager was used to install get_iplayer?)

C:\> 

The script did create a new default profile folder, in my case

  C:\Documents and Settings\TheBoss\.get_iplayer

but left it empty.  The error message clearly says that it's aborting the process (of updating plugins) because the get_iplayer perl script is not writable...     I can easily work around this, but I think the logic is wrong.  In the mainline part of the script there's this:

 # Force plugins update if no plugins found
 if ( ! keys %plugin_files && ! $opt->{packagemanager}) {
    logger "WARNING: Running the updater again to obtain plugins.\n";
    $opt->{pluginsupdate} = 1;
 }
 # Update this script if required
 update_script() if $opt->{update} || $opt->{pluginsupdate};  

which is to say:

 if no plugins found, and the app is not configured saying that it was installed with a packagemanager
     set a flag to say that 'pluginsupdate'  is required
      (that's just the same as if the user coded --pluginsupdate)

 then, call a routine named "update_script"
  if either  "--update"  or  "--pluginsupdate"
    was specified (or implied)

In the update_script subroutine there's this:

   # If the get_iplayer script is unwritable then quit - makes it harder for deb/rpm installed scripts to be overwritten
   if ( ! -w $script_file ) {
      logger "ERROR: $script_file is not writable - aborting update (maybe a package manager was used to install get_iplayer?)\n";
      exit 1;
   }

which does what it says...   Fair enough if the user asked for  --update  but if the user has explicitly asked for (or had the app set the flag itself) just --pluginsupdate   as happens on the first run of the script, it makes no sense to me to abort if the main script is read-only.  Surely the state of the main script only matters if   --update   is to be performed?

I think there's another potential problem in the updating logic; after all the tests of whether folders & files are writable, and having decided which files need update (ie where there are more recent versions than what's installed available online) the process runs file-by-file, stopping at any stage if there's a problem.  This could break a user's install if one of the downloads for a new file failed.  I think the new files all have to be downloaded ok first before the actual install logic runs.

**Comment by dinkypumpkin** [comment]
While it is possible for the files to become out of sync if one download fails, I'm not going to touch that bit.     Those plugin files are extremely unlikely to change.  More to the point, the separate plugin files (along with `--plugins-update`) are soon to go the way of the dodo.
