### ISSUE TITLE
"FLV file contains neither video nor audio" error when using --start and --stop

### ISSUE THREAD

**Issue by jpodwyer** [get-iplayer/get_iplayer#137]
I used the following string to record part of a programme....
get_iplayer --pid b05405y0 --start 00:01:00 --stop 00:26:00 --type radio --mp3 --output "d:/downloaded radio/from getiplayer/" 

when the recording passed the designated stop time the programme repeatedly displayed an error message saying there is no video or audio whereupon I terminated it.

The recorded file is named Through_the_Night_-_Bach_and_Handel_Parallel_Lives_b05405y0_default.partial.mp3 and is recognised and playable only by Realplayer. Windows Media Player for instance won't play it nor will Itunes

The intention was to record 25 minutes of a long programme
The same string works fine without the start/stop parameters

**Comment by dinkypumpkin** [comment]
The file isn't incomplete, but rather is broken(ish).  It's an FLV file (Explorer is hiding the extension), so won't play in iTunes or WMP anyway.  --start messes up the beginning of the file (the source of those error messages when rtmpdump attempts to resume what it sees as an incomplete download), so it may not play in VLC or other applications, either.  The referenced fix should avoid the errors, but it won't guarantee that the download reaches the stop time, so you should check the duration of the final file.  ffmpeg can usually still convert the damaged file to MP3, but no guarantees on that either.

rtmpdump is a poor audio file editor.  In the future, avoid using --start if possible.  Run get_iplayer with --stop and then load the final file in a proper editor to slice off the bit at the beginning.  In general, I would say not to use --stop either, but I can see where you might not want to wait on the full 6 hours of Through the Night just to get the first 25 minutes.

**Comment by jpodwyer** [comment]
Thank you for that very prompt and comprehensive diagnosis and explanation.
And I guess I will have to grin and bear it if the segment of interest is towards the end of the programme :).

**Comment by dinkypumpkin** [comment]
In the next release, `--start` and `--stop` will work better with HLS streams.  However, the BBC have removed the 320kbps HLS on-demand streams, so it forces a choice between fiddling with editing or lower quality audio.

**Comment by jpodwyer** [comment]
Thanks - look forward to it.
For what it is worth... suggest use of those options should maybe force the lower quality; users would probably  would be happy with that for the relatively few occasions when it would be used.
Thanks again
Jim
