### ISSUE TITLE
PVR: get_iplayer does not reset proxy for each pvr search

### ISSUE THREAD

**Issue by kbavishi** [get-iplayer/get_iplayer#140]
If I have a proxy setting enabled for a certain PVR search item, then get_iplayer keeps using that proxy for subsequent PVR search items also. See sample log:

```bash
$ get_iplayer --pvr

Running PVR Searches:
Book_of_the_Week
University_Challenge
INFO: Using Proxy http://195.40.6.43:3128
Words_and_music
INFO: Using Proxy http://195.40.6.43:3128
```
As per the INFO logs above, it uses the proxy for both ```University_Challenge``` and ```Words_and_music``` But I have the proxy setting enabled only for the ```University_Challenge``` item. Look for the ```<<<<< ``` marker in the output below

```bash
$ get_iplayer --pvr-list

All PVR Searches:
pvrsearch = Book_of_the_Week
	modes = flashaaclow
	output = /Users/karan/Downloads/Book_of_the_Week/
	search0 = Book of the Week
	type = radio

pvrsearch = University_Challenge
	output = /Users/karan/Downloads/UC_2014/
	proxy = http://195.40.6.43:3128                        <<<<<
	search0 = University Challenge
	subtitles = 1
	tvmode = flashstd
	type = tv

pvrsearch = Words_and_music
	modes = flashaacstd,flashaaclow
	output = /Users/karan/Downloads/Words_and_Music/
	search0 = Words and Music
	type = radio
```

**Comment by dinkypumpkin** [comment]
Fixed.  If you don't want to update your get_iplayer script, you should be able to work around this issue in v2.92 by adding `noproxy 1` to the relevant pvr job files, and using `--no-proxy` when creating new pvr jobs that shouldn't use a proxy.
