### ISSUE TITLE
Unable to download a radio show

### ISSUE THREAD

**Issue by cmpct** [get-iplayer/get_iplayer#146]
Hi,
I'm unable to download http://www.bbc.co.uk/programmes/b00kp806 (Inside the Virtual Anthill: Open Source Means Business). It says "available now", but I can't download it.

Running get_iplayer v2.92.

Does this mean that get_iplayer is failing to find it, or it's not up for digital download, or something else?

**Comment by GrahamCampbell** [comment]
No. It means the bbc are having "technical difficulties" again. It doesn't play in my browser...
