### ISSUE TITLE
Unable to find BBC One Wales with 'livetv'

### ISSUE THREAD

**Issue by cmpct** [get-iplayer/get_iplayer#151]
$ get_iplayer --type=livetv
get_iplayer v2.92, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.

Matches:
80000:	BBC Alba - live
80001:	BBC Four - live
80002:	BBC News - live
80003:	BBC One - live
80004:	BBC Parliament - live
80005:	BBC Three - live
80006:	BBC Two - live
80007:	CBBC - live
80008:	CBeebies - live
80009:	S4C - live

INFO: 10 Matching Programmes

How can I get BBC One Wales? Sometimes there are scheduling/content changes between the two channels.

**Comment by dinkypumpkin** [comment]
Please post usage queries at https://squarepenguin.co.uk/forums/
