### ISSUE TITLE
tvmodes (flashvhigh, flashhigh, flashstd) not working from outside UK

### ISSUE THREAD

**Issue by masterfish1** [get-iplayer/get_iplayer#154]
I'll first state that I'm outside the UK so this may be the issue but I don't think so as I can download in HD without issues and can also download radio as if I were in the UK so I don't think my DNS is at fault. Also I've tried two different ones and the issue is the same. I've also tried it on my Raspberry Pi and the issue is the same so it doesn't relate to my computer (even though I have uninstalled and installed it again).

If I try to download in SD it cycles through all the modes and then downloads in flashlow. This is only in the last 24 hours or so. Prior to that there was no problem.

I wonder if the BBC have made any changes.

Here is the output, I am using 2.92.

https://gist.github.com/anonymous/8ccce7bc568ee0141614

**Comment by dinkypumpkin** [comment]
HD is served differently to SD, and radio is served differently to TV, so you can't necessarily expect the same behaviour for all.  All work fine in the UK, so in all probability you've been geo-blocked.  There is nothing get_iplayer can do about that, and any further discussion of non-UK access to iPlayer is off-limits here.
