### ISSUE TITLE
PVR Hold off setting - request for info

### ISSUE THREAD

**Issue by jonandel** [get-iplayer/get_iplayer#156]
Ive searched the wiki and Googled everywhere, but cannot find how to use the 'PVR Hold Off (Hours)' in the Web manager (advanced).
Can I give it a series of comma separated, or a range of hours - e.g '9,10,15,16,17' or '9-17' so that the PVR doesnt run between these times ?

**Comment by dinkypumpkin** [comment]
Please post usage queries at https://squarepenguin.co.uk/forums/
