### ISSUE TITLE
request: possibility to search based on time since a program was available

### ISSUE THREAD

**Issue by realdmitchell** [get-iplayer/get_iplayer#158]
Hi
the "--since" now looks at time based on cache age. The problem is as follows.

I usually use get_iplayer to download only today's (I mean here "day" like current day - monday, tuesday...friday) podcast of the program "Best of Today". Assume I did NOT refresh on thurday, friday, saturday and sunday. Now on Monday, when I refresh, it assumes all podcasts from Thu-Monday as NEW and downloads them.

I would like the "--since" parameter, to use "available" (which is date) to look for what programs to download. Example file podcast.cache given here:
```
#index|type|name|pid|available|episode|seriesnum|episodenum|versions|duration|desc|channel|categories|thumbnail|timeadded|guidance|web
24114|podcast|Best of Today|http://downloads.bbc.co.uk/podcasts/radio4/today/today_20150527-0753c.mp3|Wed, 27 May 2015 07:53:00 +0100|Wednesday's business news with Simon Jack|||default|10:58|Will there be anything in the Queen's speech to help small businesses?|BBC Radio 4|News & Politics|http://www.bbc.co.uk/podcasts/assets/artwork/today.jpg|1433164317||http://www.bbc.co.uk/today|

```
The variable is then "available"=Wed, 27 May 2015 07:53:00 +0100
If this is possible, then one could search for programs between date ???? -> ????, instead of cache age.

Many thanks for your great work!

**Comment by realdmitchell** [comment]
Ok, after a bit of trying I can do this for "radio" in a different way (but not for podcasts)
```
--refresh-limit-radio  1 --refresh-feeds=schedule --type=radio  "today
```

**Comment by dinkypumpkin** [comment]
Please post feature requests at https://squarepenguin.co.uk/forums/forum/feature-requests/
