### ISSUE TITLE
Amend help text to indicate category search is not supported for TV programmes

### ISSUE THREAD

**Issue by dinkypumpkin** [get-iplayer/get_iplayer#160]
With the death of the ION data feeds (#159), the TV and radio programmes data caches no longer include category information, so `--category` and `--exclude-category` have no effect on TV searches.

**Comment by PuffinBlue** [comment]
Is this suspected to be a permanent change requiring removal of any mention of using categories or is a simple notice required on the relevant pages as a temporary measure pending a workaround to restore these features?

**Comment by dinkypumpkin** [comment]
Short answer: Category searches are gone for the foreseeable future, so removal is probably best.  Category searches would only come back to get_iplayer if it moves to scraping the iPlayer site, and that is not in the plan at this time.  Category searches will still work for podcasts, so you might qualify any instructions accordingly.
