### ISSUE TITLE
rtmpdump timeout needs to be longer

### ISSUE THREAD

**Issue by primaeval** [get-iplayer/get_iplayer#167]
I get a lot of corrupted recordings with the default rtmpdump timeout of 10 seconds, especially when my home network is busy. I increased it to 100 seconds and recordings never fail now.

push @{ $binopts->{rtmpdump} }, ( '--timeout', 100 );

**Comment by dinkypumpkin** [comment]
Use `--rtmp-tv-opts="--timeout 100"` and `--rtmp-radio-opts="--timeout 100"`
