### ISSUE TITLE
Recording from the Glastonbury streams ?

### ISSUE THREAD

**Issue by SBRK** [get-iplayer/get_iplayer#171]
Is it possible to record from the Glastonbury streams ? (ex: http://www.bbc.co.uk/events/e84mxj/live/cfmxn3)

get_iplayer "http://www.bbc.co.uk/events/e84mxj/live/cfmxn3" 
or
get_iplayer --pid=cfmxn3

both fail : "failed to get version pid metadata from iplayer site". I tried with different types, without success.

**Comment by Vangelis66** [comment]
@SBRK wrote: 

> Is it possible to record from the Glastonbury streams?

Short answer is NO :-( 
The live on-line streams on the Glasto Homepage 
use a method of delivery called "AdobeHDS", if viewed 
on a desktop browser, or "AppleHLS" if viewed on a 
compatible mobile device... 
GiP has no support at all currently for "AdobeHDS", 
and sadly can't pick up the "AppleHLS" streams 
for those Glasto live streams...
You are better advised to wait until those Glasto 
performances are uploaded onto iPlayer and then 
record them as video-on-demand (catch-up).

But to answer your original question outside the 
confines of GiP, YES, those streams are recordable 
via different means...
If you load http://www.bbc.co.uk/events/e84mxj/live/cfmxn3 
on Mozilla Firefox (currently showing Jamie T on the "Other Stage"), 
and do URL sniffing via its Web Console, you can find the 
following URLs:
 
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/journalism-pc/vpid/p02vf7ql/atk/316f68ff509aba357288dfb0f3dc7d20fe008de9/asn/1/
Akamai CDN:
http://a.files.bbci.co.uk/media/live/manifesto/audio_video/webcast/hds/uk/pc/ak/sport_stream_12.f4m
Limelight CDN:
http://a.files.bbci.co.uk/media/live/manifesto/audio_video/webcast/hds/uk/pc/llnw/sport_stream_12.f4m

If you have PHP installed in your system and also install the AdobeHDS.php script 
(https://github.com/K-S-V/Scripts/blob/master/AdobeHDS.php), you can record 
the live stream via the following command line: 
php AdobeHDS.php --manifest "http://a.files.bbci.co.uk/media/live/manifesto/audio_video/webcast/hds/uk/pc/ak/sport_stream_12.f4m" --delete (end file is FLV)
(available bitrates: 512, 796, 1296, 2096, 3500)

If you are more agile with FFmpeg, then by loading: 
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/p02vf7ql
you can retrieve: 
http://a.files.bbci.co.uk/media/live/manifesto/audio_video/webcast/hls/uk/hls_tablet/ak/sport_stream_12.m3u8
which is the master HLS playlist (available bitrates: 60, 176, 368, 496, 796, 1500); 
to grab the highest mobile bitrate, use the following command: 
ffmpeg -loglevel 16 -re -i "http://ve-hls-uk-live.bbcfmt.vo.llnwd.net/pool_13/live/uk/sport_stream_11_3/sport_stream_11_3.isml/sport_stream_11_3-track1%3d96000-video%3d1200000.m3u8?dvr_window_length=24" -c copy GlastoLive.ts (end file is TS)
NB: FFmpeg binary should be >= 2.5 branch! (older die on these BBC streams...)

 Most probably when you read my reply the live streams would have ended, 
I posted it all the same as a template of a more general "How-to" approach... 
There's ample instructions online on how to install PHP, use adobehds.php 
and ffmpeg, so do your own searches for futher assistance...

Regards

**Comment by SBRK** [comment]
Thanks for your answer !

**Comment by dinkypumpkin** [comment]
Not that it will be much help at this late hour, but you don't need to do all that.  Just view the HTML source of the page you referenced and search for the string "type=Episode&pid=" (without quotes).  The stream PID follows the "pid=".  You also need --type=livetv.  So for your example:

`get_iplayer --pid p02vf7np --type livetv`

gets the Other Stage stream.  ffmpeg 1.x versions will work, but YMMV.  You may not see a progress display while recording with ffmpeg 1.x versions.

In the future, please post usage queries at:

https://squarepenguin.co.uk/forums
