### ISSUE TITLE
Subtitles issue

### ISSUE THREAD

**Issue by Vangelis66** [get-iplayer/get_iplayer#174]
Hi - after typing:
 
<code>get_iplayer --pid=b0621y3v --modes=flashvhigh --force --raw --subtitles-only</code>

to grab the .srt subs, they indeed came down alright, but when I tried to watch the previously 
downloaded video (subs placed with same filename into same folder), the subs did not show up 
in my software player (e.g. VLC-win32 2.2.1). 
 This got me puzzled and indeed took me a while to figure out the root cause, 
but it appears it's down to a recent BBC change...
When I opened the .srt file with a text editor, the timestamps looked like this: 
__________________________________
1
07:29:32,400 --> 07:29:33,680
Koda-line.

2
07:29:33,680 --> 07:29:37,640
Kodaline. La-la-la-la. Koda...line.

etc.
__________________________________
i.e. first subs line to appear at ca. the 7h30min mark, 
and this for a 28min14sec show!

This is not a GiP fault per se, since the raw xml file already 
contains the wrong timestamps:
http://www.bbc.co.uk/iplayer/subtitles/ng/modav/bUnknown-b11dc02b-0810-4c6c-8846-92d618f216ff_b0621y3l_1436221189580.xml
but could GiP deal with this somehow to rectify beeb's fault? 
My TV downloads are scarce, so I can't say if this is a much broader 
issue with subs on iPlayer, however all episodes of the 
"CBBC Official Chart Show" currently available are affected...
Also, could you propose a solution (e.g. a script) to fix already 
downloaded subs?

Always appreciative of your hard work...
Regards.

**Comment by dinkypumpkin** [comment]
Please post usage queries at https://squarepenguin.co.uk/all-forums/
