### ISSUE TITLE
Is 4GB the max file size that can be downloaded?

### ISSUE THREAD

**Issue by shaoran** [get-iplayer/get_iplayer#179]
Hi

In the last couple of months I have noticed that the download of long (>3h) like the F1 live races almost always fails at around 85%. Today I realised that when this happens, the file is always 4 GB large. 

I have been trying to download the latest F1 http://www.bbc.co.uk/iplayer/episode/b064dcz9/formula-1-2015-the-hungarian-grand-prix on different machines (through proxy and without proxies) and everytime the file reaches 4GB I get these errors

ERROR: RTMP_ReadPacket, failed to read RTMP packet header
4185986.926 kB / 9461.48 sec (87.4%)
INFO: Connection timed out, trying to resume.

Resuming download at: 4185986.926 kB
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
4185986.926 kB / 0.00 sec
INFO: Connection timed out, trying to resume.

and that never stops, I cannot resume the download anymore. I use ext3 as file system and my system can write files larger than that (like virtualbox image files), so I don't think that my filesystem is the issue here. Could it be that rtmpdump needs some special flag (that get_iplayer isn't using) to handle files larger than 4 GB? I'm currently using RTMPDump v2.4, perhaps I should use a newer version?

**Comment by dinkypumpkin** [comment]
Please post usage queries at: https://squarepenguin.co.uk/forums/
