### ISSUE TITLE
Live streams 2 hour delayed

### ISSUE THREAD

**Issue by garethlp** [get-iplayer/get_iplayer#187]
Since upgrading the latest iPlayer channel app, my livestreams are two hour delayed -- so, for example watching BBC1 at 6am (when BBC Breakfast should be starting) it's showing programming from 4am (BBC News Channel simulcast). What's happening!?

**Comment by dinkypumpkin** [comment]
If you have problems with the iPlayer app, report them to the BBC.  get_iplayer is completely unrelated to any iPlayer app.
