### ISSUE TITLE
TV categories

### ISSUE THREAD

**Issue by neothemachine** [get-iplayer/get_iplayer#189]
In the documentation it says that `--category` is not supported for TV and radio, so I assume this information is not fetched or parsed. My personal use case would be to regularly download any TV documentaries, which seems impossible without categories as the word "documentary" is not always appearing in the title or description.

Is this technically possible? That is, is the category data available in a convenient form (not html)?

**Comment by dinkypumpkin** [comment]
Please post feature requests at: https://squarepenguin.co.uk/forums/
