### ISSUE TITLE
Support AdobeHDS 50fps file downloads 

### ISSUE THREAD

**Issue by johnuren1980** [get-iplayer/get_iplayer#190]
With a recent change, BBC iPlayer now has Adobe HDS streams available for on-demand content. Can get_iplayer support either providing the manifest file download command for [AdobeHDS.php] (https://github.com/K-S-V/Scripts/blob/master/AdobeHDS.php) or wrapping the download into the script and tidying up afterwards?

**Comment by dinkypumpkin** [comment]
Please post feature requests at: https://squarepenguin.co.uk/forums/

**Comment by dinkypumpkin** [comment]
Closed by 6f81133911381d4e22fedc6a6f16d9cc8be74d11
