### ISSUE TITLE
www.infradead.org not accessible

### ISSUE THREAD

**Issue by jhenkins** [get-iplayer/get_iplayer#201]
Does anybody know what is going in?

* This prevents a new get_iplayer installation from running
* This prevents updates and plugins from being downloaded.

**Comment by dinkypumpkin** [comment]
http://www.mail-archive.com/get_iplayer@lists.infradead.org/msg08069.html

**Comment by dinkypumpkin** [comment]
https://squarepenguin.co.uk/forums/thread-532.html
