### ISSUE TITLE
"--tvmode=hlshd" enhancement suggestion

### ISSUE THREAD

**Issue by Vangelis66** [get-iplayer/get_iplayer#204]
As per issue https://github.com/get-iplayer/get_iplayer/issues/149, commit https://github.com/get-iplayer/get_iplayer/commit/01842516a717d000a7844ea4fc7e615aebab0fd was authored last April...

It appears this "fragile" hack is no longer needed; the hlshd (V=720p25fps_A=96k_BR~2400k) stream can be accessed via (new?) mediaset="iptv-all":

http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/[vpid]

under {service="iplayer_stb_streaming_hd" & supplier="akamai_hls_open"}.

That way, access to the hlshd stream is independent of the existence of {service="pc_streaming_hd" & supplier="akamai"} that the current solution relies upon - hence it'll continue to work when the RTMP streams are completely killed off (and up until the "older" HLS streams are themselves removed in favour of the USP/Video Factory ones) ...

Kindly consider this enhancement suggestion...

Regards

**Comment by dinkypumpkin** [comment]
Already done for next release.
