### ISSUE TITLE
Update master branch to 2.95 and tag 2.95

### ISSUE THREAD

**Issue by LegoChicken** [get-iplayer/get_iplayer#212]
I've just pulled the latest version from github and it appears to still be 2.94. On github there isn't a tag for 2.94. Is it possible to update the master branch.

Thanks

**Comment by dinkypumpkin** [comment]
There is indeed a tag for 2.94 - look at the repo releases.  If you meant that there is no tag for 2.95, then you are correct - there is no get_iplayer 2.95.  If you're asking me to make a 2.95 release now, the answer is no. It will be released when it is ready.
