### ISSUE TITLE
wifi disconnects when downloading in Ubuntu

### ISSUE THREAD

**Issue by raspatan** [get-iplayer/get_iplayer#219]
The wifi stops working when downloading content. As soon as I start downloading, the wifi disconnects and I cannot reconnect again. I need to disable and enable the Wifi device to be able to reconnect. Yet, as soon as I start downloading, it crashes again. Other usage of the wifi does not crashes it (like posting this). I'm using xUbuntu 14.04.02 with the latest stable release of get iplayer (2.94-ppa23). The wifi is private. 

This just started today. In fact, earlier today I downloaded around 40% of one file, when it the wifi crashed. After restarting, I could download the rest of it. Now, when I start a new file, the wifi stops immediately after downloding a few bytes.

**Comment by raspatan** [comment]
Well, finally could download the rest of the file after waiting for a while. No idea what explains the randomness of the issue. Will leave this issue open to see if anyone has an interesting insight to add.

**Comment by dinkypumpkin** [comment]
get_iplayer has no knowledge of, and no control over, your wifi setup.  If your network device is crashing on connections to the BBC CDN streaming media servers, that is a problem with your system, and beyond get_iplayer's influence.
