### ISSUE TITLE
SELinux conflict, Fedora 23

### ISSUE THREAD

**Issue by partialenlightenment** [get-iplayer/get_iplayer#224]
Hi,

Just upgraded Fedora 21 > 23, everything was running fine before upgrade.

On running: get_iplayer --get --type=tv --url=http://www.bbc.co.uk/iplayer/episode/b06np79d/question-time-05112015
I get this.

http://pastebin.com/Du20kK09

The SELinux troubleshooting is something I can generally manage, but this one stumps me:

http://pastebin.com/UKtGvgA1

Any ideas?

Thanks!

**Comment by dinkypumpkin** [comment]
Please post support requests at: https://squarepenguin.co.uk/forums
