### ISSUE TITLE
streamurl shown for HLS stream using --streaminfo -t for catch-up TV is not a HTTP URL

### ISSUE THREAD

**Issue by thejsa** [get-iplayer/get_iplayer#226]
Hey there,
I'm having an issue with the --streaminfo option.
I need the full HTTP URL to the M3U8 HLS stream for a catch-up programme but I just get something which looks like the end of a URL and no indication as to what the beginning is.

It works fine when I try to fetch a live TV stream URL.

Command: `get_iplayer --streaminfo -t --pid=b06ptpq7` (Teletubbies) (it's for testing purposes, honest)
Output: (partial)

```
stream:     hlsstd1
audio_bitrate: 64
authstring:
bitrate:    565
expires:    2015-12-09T07:40:00Z
ext:        mp4
identifier:
kind:       video
priority:   1
server:
size:
streamer:   hls
streamurl:  vf_b06ph0h3_f2096ebf-b449-4c29-9b22-b82dc9b493d0-audio_1=96000-video=437000.m3u8?__gda__=1447089282_16b43eca9cc93e8ee1053e892814271c
swfurl:     http://emp.bbci.co.uk/emp/SMPf/1.11.16/StandardMediaPlayerChromelessFlash.swf
type:       (gip_hls_iplayer_565) hls h264 512x288 565kbps stream (CDN: mf_akamai_uk_hls/1)
video_bitrate: 501
```

Either this is a bug or I'm messing up somewhere.

**Comment by dinkypumpkin** [comment]
Fixed long ago in develop branch
