### ISSUE TITLE
Failure to tag expired audio file

### ISSUE THREAD

**Issue by Vangelis66** [get-iplayer/get_iplayer#231]
I had an FLV file on disk, which was the product 
of recording the "BBC Radio 2 Live" stream via 
KSV's AdobeHDS.php script; the recording was 
made on Saturday March 7th 2015. 
The raw ADTS (.aac) audio stream was extracted, 
edited losslessly with mp3DirectCut and muxed to 
the MP4 container with MP4Box.
The end .m4a file corresponds to the following 
Radio 2 programme (first broadcast 201503072200Z):
http://www.bbc.co.uk/programmes/b05469xc
so I gave the file the following custom name:
`Sounds Of The '80s - Sat_07_03_2015[b05469xc](liverip,llhds320).m4a`
(which contains both whitespaces and underscores).
The file was placed inside GiP's default download directory.

 I then downloaded the very latest commit of the develop 
branch of GiP and as per https://github.com/get-iplayer/get_iplayer/issues/181 
I proceeded to tag this expired radio programme 
(which was not extant in "history", as explained in the 
beginning) by issuing the CLI command (on win 32bit):

`perl get_iplayer-295dev.pl --pid=b05469xc -w --file-prefix="Sounds Of The '80s - Sat_07_03_2015[b05469xc](liverip,llhds320)" --tag-only --tag-podcast-radio`

But much to my dismay, the tagging failed:

`WARNING: Cannot tag missing file D:\Vangelis\iPlayer Recordings\Sounds Of The '80s - Sat_2015-03-07[b05469xc](liverip,llhds320).EXT`

As you can see, the script has changed my custom "--file-prefix" string 
("Sat_07_03_2015" => "Sat_2015-03-07") and thus failed to find the 
file to be tagged...
Is this a bug or an intended behaviour?
If I rename my file so as not to contain underscores:
`Sounds Of The '80s - Sat 07 03 2015[b05469xc](liverip,llhds320).m4a`
then the MP4 tagging succeeds:

`perl get_iplayer-295dev.pl --pid=b05469xc -w --file-prefix="Sounds Of The '80s - Sat 07 03 2015[b05469xc](liverip,llhds320)" --tag-only --tag-podcast-radio`

    INFO: Tagging file D:\Vangelis\iPlayer Recordings\Sounds Of The '80s - Sat 07 03
    2015[b05469xc](liverip,llhds320).m4a
    INFO: MP4 tagging M4A file
    
    Started writing to temp file.
    Progress: =============================================>100%|
    Finished writing to temp file.
    
    INFO: 1 Matching Programmes
  Am I to accept that whitespaces and underscores 
can't be both present or is this fixable?

Many thanks for your continued efforts 
into keeping this project still alive :thumbsup:

**Comment by dinkypumpkin** [comment]
Please post usage queries at: https://squarepenguin.co.uk/forums/
