### ISSUE TITLE
Unable to download from BBC News website

### ISSUE THREAD

**Issue by cheater** [get-iplayer/get_iplayer#235]
Hi,
It appears to me that the BBC News website should likely be using similar methods of streaming video as iPlayer. I would like to be able to do something like:

get_iplayer http://www.example.com/news/uk-35269318

(replace example with bbc) (i used xxx before example and that led to a funny site)

in order to get the video on that news page.

**Comment by dinkypumpkin** [comment]
Post support requests at: https://squarepenguin.co.uk/forums/
