### ISSUE TITLE
DASH recording fails when number of segments is miscalculated

### ISSUE THREAD

**Issue by jscholes** [get-iplayer/get_iplayer#237]
When GiP miscalculates the total number of DASH segments to be downloaded and mistakenly adds an extra one resulting in an HTTP/404, recording fails, even though the entire program has probably been fetched and can be safely renamed, converted and tagged.  GiP should distinguish between a segment not being found, i.e. probably not existing for download, and a more serious error such as an HTTP/500.

An example of this can be seen in the attached debug log.
[debug.log.txt](https://github.com/get-iplayer/get_iplayer/files/85208/debug.log.txt)

**Comment by dinkypumpkin** [comment]
I don't think it is a miscalculation per se - the BBC DASH player displays the same behaviour - but if you see the flaw in the arithmetic, don't be shy about pointing it out. There might be something special about having a programme duration that is an integer multiple of the segment duration, but I don't know what it would be - probably just slightly erroneous manifest data. I was wondering if the manifest data would be accurate enough to generate segment lists - I guess I have my answer. No choice but to do as you suggest and make 404s non-fatal. Better to go too long than too short.
