### ISSUE TITLE
WARNING: Failed to download programme schedule

### ISSUE THREAD

**Issue by xplora1a** [get-iplayer/get_iplayer#238]
The feeds for get-iplayer have been disabled. Now get the message:
"This service is currently undergoing a period of downtime for essential maintenance. Please be advised that the programme information service which is currently available at this URL will soon be replaced by a new service from the BBC, at a new set of URLs. Please contact the following email address for further information: 'programmes-devel@lists.forge.bbc.co.uk'"

**Comment by TomK32** [comment]
Interestingly there are json files: http://www.bbc.co.uk/iplayer/episode/b06wj608.json

**Comment by dinkypumpkin** [comment]
Normal service has been restored for now - get_iplayer should be working again.
