### ISSUE TITLE
Allow custom tagging using substitution parameters

### ISSUE THREAD

**Issue by jawj** [get-iplayer/get_iplayer#243]
Suggestion: how about enabling custom tagging, using substitution parameters?

The particular use case I have right now is that my router's DLNA server sorts programmes by their title tag, and I therefore need a title tag like this: `<00episodenum>._<episodeshort>`

At the moment I use `--tag-longepisode`, but this means it sorts like this:

1. Blah
10. Thing
11. Other thing
2. Etc

I was surprised this didn't seem to be supported already. Or perhaps it is, and I have stupidly missed it ... ?

**Comment by dinkypumpkin** [comment]
Post feature requests at: https://squarepenguin.co.uk/forums/
