### ISSUE TITLE
Only get relevant mediaselector playlists when mode is specified

### ISSUE THREAD

**Issue by horsemule** [get-iplayer/get_iplayer#244]
When I specify that I want flashhd mode (modes or tvmode)

get_iplayer gets:
http://open.live..../mediaselector/5/select/version/2.0/mediaset/pc/vpid/XXX/proto/rtmp

But it also gets many other URLs/playlists which are not relevant to the rtmp/flash format:

/mediaset/apple-ipad-hls
/audiodesc/modav/XXXX.mp4/master.m3u8
mobile_wifi_main_sd_abr_v1_hls_master.m3u8
...

(some of which are 403 forbidden, or Invalid HLS playlist, no header)

But I have no interest in HLS or other formats when I specify flashhd.

If HLS were to be explicitly specified as the desired mode then I wouldn't want the rtmp ones.

**Comment by dinkypumpkin** [comment]
Post feature requests at: https://squarepenguin.co.uk/forums/
