### ISSUE TITLE
Overlapping index numbers for tv and radio

### ISSUE THREAD

**Issue by sthen** [get-iplayer/get_iplayer#247]
03c5313fd18d0f changed the index_max for tv from 9999 to 19999, but this overlaps radio (10001..39999). So now, when fetching a radio programme with an index from 10001..19999, the code under the "Go get the cached data for other programme types if the index numbers require it" comment has to also retrieve tv listings.

**Comment by dinkypumpkin** [comment]
Thanks for the report
