### ISSUE TITLE
BBC appear to be about to remove RMTP access

### ISSUE THREAD

**Issue by PaulWebster** [get-iplayer/get_iplayer#248]
For info ... BBC blog post of 1st Feb 2015

> This development will also see the demise of RTMP as a delivery method for on-demand radio in BBC products. This has never been sanctioned for use in anything other than BBC products so if you're using it for your own stuff you shouldn't be and please consider this fair warning that it will be stopping soon without any further notice.

http://www.bbc.co.uk/blogs/internet/entries/f21e6a49-e53c-44f0-8b01-09890a8fed8f

**Comment by dinkypumpkin** [comment]
Post support issues at: https://squarepenguin.co.uk/forums/
