### ISSUE TITLE
Enable download over port 80 in the GUI

### ISSUE THREAD

**Issue by midas02** [get-iplayer/get_iplayer#249]
I recently bumped into a problem. Using a hotspot, port 1935 was blocked, and therefore rtmpdump couldn't download the source file. It was only by consulting the documentation that I found out I could force rtmpdump from the command line to use port 80.

I checked the GUI again, but the option to download over port 80 doesn't seem to be presented to the user. Maybe I'm missing something, but wouldn't it make sense to add a button in the GUI allowing the user to select the port he wishes to download over?

**Comment by dinkypumpkin** [comment]
Post feature requests at: https://squarepenguin.co.uk/forums/
