### ISSUE TITLE
BBC iPlayer Schedule Pages

### ISSUE THREAD

**Issue by 1701Will** [get-iplayer/get_iplayer#251]
I put the website address in for one of the schedule pages (http://www.bbc.co.uk/bbcfour/programmes/schedules/last_week.xml) and it said:

This service is currently undergoing a period of downtime for essential maintenance. Please be advised that the programme information service which is currently available at this URL will soon be replaced by a new service from the BBC, at a new set of URLs. Please contact the following email address for further information: 'programmes-devel@lists.forge.bbc.co.uk'

**Comment by dinkypumpkin** [comment]
Thanks.  Closing in favour of #239
