### ISSUE TITLE
Recent Commit Changed 50fps Rip?

### ISSUE THREAD

**Issue by itzeddie** [get-iplayer/get_iplayer#253]
Hey folks,

Just updated to the latest version of the dev branch and am up to date and I noticed that you change the modes to best hls and hvf, I have noticed since this change that "hlsbest" no longer downloads 50fps content, is that correct? I have also noticed that hvf rips seem to be going exceptionally slow on both workstations I run the latest build.

EDIT: I notice in an earlier commit you added hls50hd, I am assuming that was removed with the commit to tweak the mode list on February 9th, as I don't get that mode either.

EDIT 2: Unsure why, when using hvfbest with raw set it creates a mp4 file instead of .ts, unsure if thats intentional or not.

Cheers,

Eddie

**Comment by dinkypumpkin** [comment]
Post support requests at: https://squarepenguin.co.uk/forums/
