### ISSUE TITLE
Can't use get_iplayer on UK server anymore

### ISSUE THREAD

**Issue by SamusAranX** [get-iplayer/get_iplayer#254]
I have a server in the UK that I use both for hosting and as my personal VPN server.
I just downloaded the develop branch version of get_iplayer and tried the following:

	me@myserver:~/get_iplayer-develop# ./get_iplayer --type=livetv --stream 80002 --debug
	get_iplayer 2.95-dev, Copyright (C) 2008-2010 Phil Lewis
	  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
	  This is free software, and you are welcome to redistribute it under certain
	  conditions; use --conditions for details.

	INFO: encodinglocale = UTF-8
	INFO: encodinglocalefs = UTF-8
	INFO: encodingconsoleout = UTF-8
	INFO: encodingconsolein = UTF-8
	INFO: ${^UNICODE} = 0
	INFO: User prefs dir: /me/.get_iplayer
	INFO: System options dir: /etc/get_iplayer/options
	Current options:
		debug = 1
		encodingconsolein = UTF-8
		encodingconsoleout = UTF-8
		encodinglocale = UTF-8
		encodinglocalefs = UTF-8
		isodate = 1
		nowrite = 1
		stdout = 1
		type = livetv
		verbose = 1

	INFO: Search args: '80002'
	DEBUG: Looking for index 80002 in livetv type
	INFO: Additionally getting cached programme data for livetv
	INFO: Cache format from existing livetv cache file: index,type,name,pid,available,episode,seriesnum,episodenum,versions,duration,desc,channel,categories,thumbnail,timeadded,guidance,web
	INFO: Got 16 file cache entries for livetv
	DEBUG: Cache expiry time for livetv is 14400 secs - refresh in 14053 secs
	DEBUG: Using desktop user-agent string: 'Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko'
	DEBUG: Using NoCookies user-agent 'Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko'
	Matches:
	80002:	BBC News - live

	INFO: 1 Matching Programmes
	DEBUG: Using desktop user-agent string: 'Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko'
	DEBUG: Using cookies.desktop user-agent 'Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko'
	DEBUG: Getting Metadata for bbc_news24:
	INFO: Using livetv: bbc_news_channel_hd
	DEBUG: Using desktop user-agent string: 'Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko'
	DEBUG: Using cookies.desktop user-agent 'Mozilla/5.0 (IE 11.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko'
	INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/bbc_news_channel_hd/transferformat/hls?cb=02387

	INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/bbc_news_channel_hd/transferformat/hls?cb=09954

	INFO: No streams available for 'default' version (bbc_news_channel_hd) - skipping RDF
	INFO: No streams available for 'default' version (bbc_news_channel_hd) - deleting
	WARNING: No programme versions found with media streams for requested modes
	WARNING: You may receive this message if you are using get_iplayer outside the UK
	ERROR: Could not get programme metadata

Did the BBC ramp up their anti-VPN measures or am I doing something wrong?

**Comment by SamusAranX** [comment]
Checking `http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/bbc_news_channel_hd/transferformat/hls?cb=09954` in my browser, I found this:

    <mediaSelection xmlns="http://bbc.co.uk/2008/mp/mediaselection">
        <error id="geolocation"/>
    </mediaSelection>

Is there any way around this? My server is physically in the UK, so I'm not sure where they're getting the geolocation thing from.

**Comment by dinkypumpkin** [comment]
Post support requests at: https://squarepenguin.co.uk/forums/

**Comment by dinkypumpkin** [comment]
Sorry - don't bother posting in forums. Geolocation evasion not a permitted topic.
