### ISSUE TITLE
unable to run non-root

### ISSUE THREAD

**Issue by githubgnulinux** [get-iplayer/get_iplayer#255]
gnu/linux command terminal error:
Bareword found where operator expected at /nonroot/user/.get_iplayer/plugins/podcast.plugin line 2, near """ lang"
	(Missing operator before lang?)
Bareword found where operator expected at /nonroot/user/.get_iplayer/plugins/podcast.plugin line 20, near "<title>get_iplayer"
	(Missing operator before get_iplayer?)
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 49 at /nonroot/user/.get_iplayer/plugins/podcast.plugin line 20.
Compilation failed in require at /local/disk/usr/path/to/get_iplayer-2.94/get_iplayer line 465.

**Comment by dinkypumpkin** [comment]
Post support requests at: https://squarepenguin.co.uk/forums/
