### ISSUE TITLE
add Nitro interface to get-iplayer

### ISSUE THREAD

**Issue by xplora1a** [get-iplayer/get_iplayer#258]
At the moment Nitro api keys are only available to internal BBC staff according to the header on the developer page:  https://developer.bbc.co.uk/nitro
"The BBC Developer site is currently open for registration to BBC Employees. Account requests from other users are not currently being activated. Please check back soon for more info."

We should start to develop a Nitro interface for get-iplayer for when this interface is opened up. 
The API documents are available: https://developer.bbc.co.uk/sites/default/files/Nitro%20for%20Clients.pdf but the schema at http://nitro.api.bbci.co.uk/nitro/api/schema is not available without an API key. There is not enough info in the For Clients document to do a complete design, but enough to map out a structure. When the API schema is open we can progress.

**Comment by dinkypumpkin** [comment]
Post feature requests at: https://squarepenguin.co.uk/forums/
