### ISSUE TITLE
How to download all episodes of a podcast?

### ISSUE THREAD

**Issue by hickford** [get-iplayer/get_iplayer#262]
Hi. I'd like to download all the episodes of a podcast http://www.bbc.co.uk/programmes/b01nmlh2/episodes/downloads

Can I do this with get_iplayer? I tried

    get_iplayer -g --pid-recursive http://www.bbc.co.uk/programmes/b01nmlh2/episodes/downloads

which correctly listed the episodes, but didn't download anything.

**Comment by hickford** [comment]
Ideally, if possible, I'd like to keep the podcast file names (`ThePublicPhilosopher-20150314-WhyDemocracy.mp3` rather than `The_Public_Philosopher_-_Why_Democracy_p02r6kzp`) because they sort by date order.

**Comment by dinkypumpkin** [comment]
Post support requests at: https://squarepenguin.co.uk/forums/
