### ISSUE TITLE
Wrong subtitles might be downloaded if multiple programme versions are present

### ISSUE THREAD

**Issue by vngvimgr** [get-iplayer/get_iplayer#263]
When using get_iplayer 2.94 or the development version 2.95, the wrong version of the subtitles might be downloaded, e. g. for the current episode of Top Gear:

`get_iplayer --pid b07dwp1f --get --subtitles`

downloads the 'original' version of the programme by default, but either the subtitles for the 'original' version or for the 'shortened' version, in an apparently non-deterministic fashion. Even a more explicit

`get_iplayer --pid b07dwp1f --get --versions=original --subtitles`

seems to randomly alternate between the two different sets of subtitles.

As far as I can tell, `download_subtitles`, the subroutine responsible for finding and downloading the subtitles, simply takes the first subtitle URL it is able to find, which might apparently change for different runs of get_iplayer and does not have to be the appropriate one for the selected version of the programme.

**Comment by dinkypumpkin** [comment]
Thanks for the report.
