### ISSUE TITLE
Transcoding failing

### ISSUE THREAD

**Issue by satscape** [get-iplayer/get_iplayer#300]
Version 2.96
The downloading phase is working, but when it comes to transcoding, it fails, I tried multiple programmes.

```
INFO: Begin recording file: The_Return_of_Flying_Scotsman_-__b073c7r0_original.partial.mp4.ts
INFO: Recorded: 1016.76MB in 00:06:16 at 22152kbps to The_Return_of_Flying_Scotsman_-__b073c7r0_original.partial.mp4.ts
INFO: Begin converting file: The_Return_of_Flying_Scotsman_-__b073c7r0_original.partial.mp4.ts
At least one input file must be specified
INFO: Command exit code 1 (raw code = 256)
```

Is this an FFMPEG issue?
If I use the --raw option in get_iplayer to skip encoding and then encode the file myself with ffmpeg it works. If you need any further output text, let me know.

**Comment by dinkypumpkin** [comment]
Post support requests at: https://squarepenguin.co.uk/forums/
