### ISSUE TITLE
Globally available clip blocked by GiP

### ISSUE THREAD

**Issue by Vangelis66** [get-iplayer/get_iplayer#307]
> Do not use this issue tracker OR the support forums if:
> - get_iplayer does not work outside the UK 

... Well, I beg to differ, but please stay with me: 

Frequently, the BBC issues excerpts of TV programmes (and other video content) as short video clips; 
quite often, rights permitting, these are made available globally via dedicated overseas streams.
One such clip is [The mystery of methane on Mars](http://www.bbc.co.uk/programmes/p04fzkxc), which can be freely viewed from a non-UK location.
As a proof to the UK-based developer, I am attaching downloaded "mediaselector" pages 
(extensions changed to .txt so they could be palatable to Github):
pid=p04fzkxc => vpid=p04fzky0
mediaselector=pc => [p04fzky0-pc.xml.txt](https://github.com/get-iplayer/get_iplayer/files/588427/p04fzky0-pc.xml.txt) (RTMP streams) 
mediaselector=apple-ipad-hls => [p04fzky0_ipad.xml.txt](https://github.com/get-iplayer/get_iplayer/files/588429/p04fzky0_ipad.xml.txt) (AppleHLS streams)

However, when attempting to fetch said clip to disk: 
`perl get_iplayer-297w.pl --pid=p04fzkxc --tvmode=hlsbest` => 
```
get_iplayer 2.97-windows.0, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.

INFO: Episode-only pid detected
INFO: Trying pid: p04fzkxc using type: tv
INFO: Trying to stream pid using type tv
INFO: pid not found in tv cache
Matches:

INFO: 1 Matching Programmes
WARNING: No media streams found for requested programme versions and recording m
odes.
WARNING: The BBC has blocked access to this programme because it has determined
that you are using get_iplayer outside the UK.
```
Actually, the same behaviour is exhibited by all GiP versions after tag 2.94, 
while GiP  2.94 itself functions as expected (by me, at least): 
`perl get_iplayer-294.pl --pid=p04fzkxc -i | FindStr modes` => 
`modes:          default: flashhigh1,flashstd1,flashvhigh1,hlshigh1,hlslow1,hlsstd1,hlsvhigh1`

Either the developer has taken it upon himself to block content 
the Beeb have legitimately made available to international audiences 
or this is an inadvertent bug, probably caused by https://github.com/get-iplayer/get_iplayer/commit/cd023e0c5ae8df3ddda6fef9fce6a5aec7438507 that was pushed 
after the 2.94 release, hence still present in versions 2.95+. 

Whichever the case, the statement generated by GiP 2.95+ : 
**WARNING: The BBC has blocked access to this programme** 
could not have been furthest from the truth!

Most kind regards.

**Comment by dinkypumpkin** [comment]
If that clip works in your browser, good for you. If you had bothered to read the code, you would know that get_iplayer only prints the "blocked access" message when the mediaselector response contains a geolocation error code, which is the one and only truth for get_iplayer. If you know how to make it work with get_iplayer, submit a pull request.

You would be well-advised avoid unwarranted accusations like this:
> the developer has taken it upon himself to block content
> the Beeb have legitimately made available to international audiences
If you do it again, expect to be blocked.
