### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by bhcopeland** [get-iplayer/get_iplayer#317]
Is there a way to get a date format to be dd/mm/yyyy.

I am trying to get http://www.bbc.co.uk/iplayer/episodes/b006m9ry but get_iplayer makes the date iso formart which makes all the tagging, as eps names are released as date format.

For example: Click-14-01-2017

In the docs 

> If you do not wish to convert dates for some reason, use the --no-isodate option [DEPRECATED].

**Comment by dinkypumpkin** [comment]
Post support requests at: https://squarepenguin.co.uk/forums/
