### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by Pen-Ace** [get-iplayer/get_iplayer#325]
Maintenance mode

APS is now supported on a UK-office-hours basis only. In the event of any outages, your attention is drawn to Clause 4 of the licence under which this service was provided, at its inception in 2007: http://www.bbc.co.uk/blogs/bbcbackstage/2005/05/api-licence.shtml.

In May 2017, regrettably, this system will permanently cease producing XML and rdf outputs. A JSON service will be kept in place for a period following this but due to budgetary and strategic considerations beyond the domain of the team which has been maintaining the system which produces these feeds. Thus the long-term availability of programme metadata, in any format, at this location, is no longer guaranteed. Other options for meeting the generic requirements which the feeds have met are under consideration, elsewhere in the BBC.

If you wish to contact the BBC on this specific matter, please address any email to programmes-devel@lists.forge.bbc.co.uk

URL http://www.bbc.co.uk/bbctwo/programmes/schedules/wales/this_week.xml

what is the workaround for this??

**Comment by dinkypumpkin** [comment]
Post support requests at: https://squarepenguin.co.uk/forums/
