### ISSUE TITLE
Allow get_iplayer CLI to run from any folder on Windows

### ISSUE THREAD

**Issue by hickford** [get-iplayer/get_iplayer#36]
I installed get_iplayer on Windows. I tried adding `C:\Program Files (x86)\get_iplayer` to my path so I could run the command `get_iplayer` more easily. It turns out, the script assumes the working directory will always be the installation folder, and fails otherwise.

> Can't open perl script "get_iplayer.pl": No such file or directory

It would be cool if `get_iplayer` worked from anywhere.

**Comment by patronanejo** [comment]
<b>I have a solution</b> for you. It requires no changes to be made to installed components and incidentally serves as a time- and keystroke-saving enhancement for command-line users of `get_iplayer`. It's simple enough, but I'll describe it in numbered steps to make it as clear as possible:

1. Add `C:\Program Files (x86)\get_iplayer` to PATH
2. Using any text editor create the file `bbc.cmd` and paste in the following code:

    `@echo off`
    `cd %programfiles(x86)%/get_iplayer`
    `cmd /k perl.exe get_iplayer.pl %*`

3. Save the file `bbc.cmd` in the folder `C:\Program Files (x86)\get_iplayer`.

<b>This essentially supplements</b> the command `get_iplayer` with the drop-in replacement command `bbc.cmd` which has the following advantages:

1. Adding a new command makes it unnecessary to risk breaking existing commands
2. The new command includes a `cd` change directory operation _so it works from anywhere_, per your request
3. The new command `bbc` is eight keystrokes shorter than `get_iplayer` and eliminates the need to type the underscore every time you wish to run get_iplayer
4. Nothing else changes; simply type `bbc` in place of `get_iplayer` at the beginning of your command-line instruction string, e.g.,
    `bbc --pid b05pwgt2 --modes best -o "C:\username\iPlayer Recordings\Malaysian_Grand_Prix_-_b05pwgt2_default.flv"`

    instead of
    `get_iplayer --pid b05pwgt2 --modes best -o "C:\username\iPlayer Recordings\Malaysian_Grand_ Prix_-_b05pwgt2_default.flv"`

<b>If you'd rather</b> continue to type out `get_iplayer` in your command line, you can edit the contents of `get_iplayer.cmd`, overwriting them with the instructions I provided for the command `bbc.cmd`. I don't recommend trusting a complete stranger (me) not to break your original command. If you need to restore it, these are the original instructions in `get_iplayer.cmd`:

    `@echo off`
    `perl.exe get_iplayer.pl %*`

**Comment by dinkypumpkin** [comment]
Closed by https://github.com/get-iplayer/get_iplayer_win32/releases/tag/2.95.0
