### ISSUE TITLE
Installer attempts to launch non-existent shortcut

### ISSUE THREAD

**Issue by Philip-Taylor** [get-iplayer/get_iplayer#370]
The 3.26 Windows x-84 installer optionally attempts to launch C:\ProgramData\Microsoft\Windows\Start Menu\Programs\get_iplayer\help\get_iplayer Documentation.url at end of installation, but that file does not exist.  The "help" sub-directory is never created, and all shortcuts are one level higher in the hierarchy.

**Comment by notnac** [comment]
Fixed in [3.27.0](https://github.com/get-iplayer/get_iplayer_win32/releases/tag/3.27.0)
