### ISSUE TITLE
[mp3_mf @ 0000000000573fc0] could not find any MFT for the given media type]

### ISSUE THREAD

**Issue by Taylor-Philip** [get-iplayer/get_iplayer#374]
Installed get_iplayer 3.27 - 2021-02-15 and tried using the web-based interface for the first time.  Told GIP to search only radio programmes and to look for "Madhur".  Found series of interest (An Invitation to Indian Cookery by Madhur Jaffrey, PID m000rty3) and told the web interface to download the whole series.  Found at the bottom of the CMD window the following error diagnostics :

                    : PLAY: https://www.bbc.co.uk/programmes/m000rty2
                    :
                    : INFO: https://www.bbc.co.uk/programmes/m000rty2
  Duration: 00:13:45.71, start: 0.000000, bitrate: 320 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, flt
p, 317 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown),
 1920x1080 [SAR 72:72 DAR 16:9], 90k tbr, 90k tbn, 90k tbc (attached pic)
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> mp3 (mp3_mf))
Press [q] to stop, [?] for help
[mp3_mf @ 0000000000573fc0] could not find any MFT for the given media type
[mp3_mf @ 0000000000573fc0] could not create MFT
Error initializing output stream 0:0 -- Error while opening encoder for output s
tream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
INFO: Command exit code 1
INFO: Finished Streaming and transcoding C:\Users\Omnipotent\Desktop\iPlayer Rec
ordings\An_Invitation_to_Indian_Cooking_by_Madhur_Jaffrey_-_01._Episode_1_m000rt
y2_original.m4a to browser

UNIV:  Windows 7 64-bit Enterprise; SeaMonkey 2.53.6

**Comment by notnac** [comment]
Fixed in [3.27.1](https://github.com/get-iplayer/get_iplayer_win32/releases/tag/3.27.1)
