### ISSUE TITLE
(very) minor error in documentation

### ISSUE THREAD

**Issue by martin-zima** [get-iplayer/get_iplayer#382]
Hi guys,

Just thought I should let you know that (I believe) there is an error on the wiki page <https://github.com/get-iplayer/get_iplayer/wiki/utils>...

The first prefs example reads...
`get_iplayer --prefs-add`
        `--ffmpeg="C:\Program Files\ffmpeg\ffmpeg.exe"`
        `--ffmpeg="C:\Program Files\atomicparsley\AtomicParsley.exe"`

However am assuming the second --ffmpeg parameter is an error and the line should instead read...
`get_iplayer --prefs-add`
        `--ffmpeg="C:\Program Files\ffmpeg\ffmpeg.exe"`
        `--atomicparsley="C:\Program Files\atomicparsley\AtomicParsley.exe"`

**Comment by notnac** [comment]
fixed
