### ISSUE TITLE
Only Downloading BSL Signed Version While iPlayer Provides Default Version

### ISSUE THREAD

**Issue by Popeye013** [get-iplayer/get_iplayer#439]
### Do not file a bug report if you are using get_iplayer outside the UK. If you do, your report will be ignored.

- [X] I am not using get_iplayer outside the UK

### Do not file a bug report if you are using get_iplayer with a VPN or proxy from any location, including the UK. If you do, your report will be ignored.

- [X] I am not using get_iplayer with a VPN or proxy from any location, including the UK

### Search the repository (search field at top left) to see if a report already exists for the bug in the issue tracker. Do not create a duplicate report. Duplicate reports will be ignored.

- [X] I have searched the repository and found no existing reports of the bug in the issue tracker

### Review recent open and closed entries in the issue tracker to see if a report already exists for the bug. Do not create a duplicate report. Duplicate reports will be ignored.

- [X] I have reviewed recent open and closed entries in the issue tracker and found no existing reports of the bug

### Ensure that you are using get_iplayer 3.31 or higher. If not, your report will be ignored.

- [X] I am using get_iplayer 3.31 or higher

### Identify the operating system and version where get_iplayer demonstrates the bug

Windows 11

### Provide a clear and concise description of the bug. Do not paste get_iplayer output or screenshots into the field below. If you do, your report will be ignored.

get_iplayer is only downloading the BSL in-vision signed version, regardless of preferences and settings.

### Provide the PID or URL of the programme you are attempting to download, if applicable. Provide the PID or URL for only one programme.

p09cvkf9

### Provide the complete get_iplayer command line that demonstrates the bug. Do not truncate or excerpt the command. If you do, your report will be ignored. If you are using the Web PVR, list the steps necessary to reproduce the bug, in as much detail as possible.

There is no command line that demonstrates the bug that im aware of (Im a bit of a noob, apologies) 

### Drag the log file into the field below to create an attachment. The log file must be added as an attachment. Do not paste its contents into the field below. If you do, your report will be ignored. You may enter a URL linking to your log file on a pastebin site. If the bug prevents get_iplayer from running, enter "N/A" in the field below. If you enter any other text in the field below, your report will be ignored.

[INFO Start 2023-08-04T161646 (16911.txt](https://github.com/get-iplayer/get_iplayer/files/12262147/INFO.Start.2023-08-04T161646.16911.txt)

**Comment by notnac** [comment]
A workaround for this episode (and likely for others in the series) is to pick out a specific set of streams for the desired programme version (they are usually merged together). First, display the episode info with:

    get_iplayer --pid=p09cvkf9 --no-merge-versions --info

and look for the line prefixed with "versions:"

    versions:        audiodescribed,audiodescribed2,editorial2,editorial3,editorial4,editorial6,signed,signed2

Start with the highest-numbered non-audiodescribed, non-signed version ("editorial6" in this example):

    get_iplayer --pid=p09cvkf9 --no-merge-versions --versions=editorial6

If that still doesn't download the desired version, work backwards through "editorial4", "editorial3", etc., until you find it.
