### ISSUE TITLE
The keyword 'default' does not appear to work with option '--versions' (Changed since v3.31)

### ISSUE THREAD

**Issue by retep** [get-iplayer/get_iplayer#446]
### Do not file a bug report if you are using get_iplayer outside the UK. If you do, your report will be ignored.

- [X] I am not using get_iplayer outside the UK

### Do not file a bug report if you are using get_iplayer with a VPN or proxy from any location, including the UK. If you do, your report will be ignored.

- [X] I am not using get_iplayer with a VPN or proxy from any location, including the UK

### Search the repository (search field at top left) to see if a report already exists for the bug in the issue tracker. Do not create a duplicate report. Duplicate reports will be ignored.

- [X] I have searched the repository and found no existing reports of the bug in the issue tracker

### Review recent open and closed entries in the issue tracker to see if a report already exists for the bug. Do not create a duplicate report. Duplicate reports will be ignored.

- [X] I have reviewed recent open and closed entries in the issue tracker and found no existing reports of the bug

### Ensure that you are using get_iplayer 3.33 or higher. If not, your report will be ignored.

- [X] I am using get_iplayer 3.33 or higher

### Identify the operating system and version where get_iplayer demonstrates the bug

Raspbian GNU/Linux" VERSION 10 (buster)

### Provide a clear and concise description of the bug. Do not paste get_iplayer output or screenshots into the field below. If you do, your report will be ignored.

get_iplayer (**GiP**) version 3.33 does not accept the parameter `--versions default`  on the command line.
**GiP** versions upto and including 3.31 accepted this parameter
This applies to both the download of radio and tv programmes

The output from running the example command (below) ends with the line : 
`WARNING: No programmes are available for this PID with version(s): default (available versions: podcast,original)`
 

The help text available from **GiP** implies that this is a valid parameter
`get-iplayer --helplong |grep -i -e "--versions"`

The change logs for versions 3.32 and 3.33 do not mention this is a change from version 3.31

### Provide the PID or URL of the programme you are attempting to download, if applicable. Provide the PID or URL for only one programme.

m001rh6c

### Provide the complete get_iplayer command line that demonstrates the bug. Do not truncate or excerpt the command. If you do, your report will be ignored. If you are using the Web PVR, list the steps necessary to reproduce the bug, in as much detail as possible.

`get_iplayer_3.33 --output-radio . --type radio --force --versions default --pid m001rh6c --get`

### Drag your verbose log file into the field below to create an attachment. Your verbose log file must be added as an attachment. Do not paste its contents into the field below. If you do, your report will be ignored. You may enter a URL linking to your verbose log file on a pastebin site. If the bug prevents get_iplayer from running, enter "N/A" in the field below. If you enter any other text in the field below, your report will be ignored.

[log.txt](https://github.com/get-iplayer/get_iplayer/files/13061233/log.txt)

**Comment by notnac** [comment]
Workaround: omit `--versions=default` from the command line. There is a bug, but there also is never a reason to use `--versions=default` on the command line unless you are overriding saved settings, and there is virtually never a useful reason to save the `--versions` setting  for radio programmes .
