### ISSUE TITLE
"Wide character" error caused by non-ASCII characters in --tag-only-filename

### ISSUE THREAD

**Issue by ilaw138** [get-iplayer/get_iplayer#448]
### Do not file a bug report if you are using get_iplayer outside the UK. If you do, your report will be ignored.

- [X] I am not using get_iplayer outside the UK

### Do not file a bug report if you are using get_iplayer with a VPN or proxy from any location, including the UK. If you do, your report will be ignored.

- [X] I am not using get_iplayer with a VPN or proxy from any location, including the UK

### Search the repository (search field at top left) to see if a report already exists for the bug in the issue tracker. Do not create a duplicate report. Duplicate reports will be ignored.

- [X] I have searched the repository and found no existing reports of the bug in the issue tracker

### Review recent open and closed entries in the issue tracker to see if a report already exists for the bug. Do not create a duplicate report. Duplicate reports will be ignored.

- [X] I have reviewed recent open and closed entries in the issue tracker and found no existing reports of the bug

### Ensure that you are using get_iplayer 3.34 or higher. If not, your report will be ignored.

- [X] I am using get_iplayer 3.34 or higher

### Identify the operating system and version where get_iplayer demonstrates the bug

Mac OSX 10.14.6

### Provide a clear and concise description of the bug. Do not paste get_iplayer output or screenshots into the field below. If you do, your report will be ignored.

When running a script to download metadata only jog files are downloaded.

jpg files are not merged to the video file and no other metadata is downloaded.

Same error occurs when run at the command line.

The error is - "Wide character at /usr/local/get_iplayer/perl/bin/get_iplayer line 2455."

Script running is - "get_iplayer --tag-only --thumbnail-square --tag-only-filename /Volumes/2\ For\ Review\ ∂/All_Is_True_-__m000yhk2_original.mp4 --pid=m000yhk2"

Output to terminal is - "get_iplayer 3.34.0-darwin
  Copyright (C) 2008-2010 Phil Lewis, 2010- get_iplayer contributors
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.

Episodes:
All Is True - -, BBC Four, m000yhk2
INFO: 1 total programmes

INFO: Processing tv: 'All Is True - - (m000yhk2)'
Wide character at /usr/local/get_iplayer/perl/bin/get_iplayer line 2455."

Previous version 3.31.0 did not exhibit this behaviour.

As this is my first post of a bug report, I hope that I have followed all of your guidelines.

### Provide the PID or URL of the programme you are attempting to download, if applicable. Provide the PID or URL for only one programme.

m000yhk2

### Provide the complete get_iplayer command line that demonstrates the bug. Do not truncate or excerpt the command. If you do, your report will be ignored. If you are using the Web PVR, list the steps necessary to reproduce the bug, in as much detail as possible.

get_iplayer --tag-only --thumbnail-square --tag-only-filename /Volumes/2\ For\ Review\ ∂/All_Is_True_-__m000yhk2_original.mp4 --pid=m000yhk2

### Drag your verbose log file into the field below to create an attachment. Your verbose log file must be added as an attachment. Do not paste its contents into the field below. If you do, your report will be ignored. You may enter a URL linking to your verbose log file on a pastebin site. If the bug prevents get_iplayer from running, enter "N/A" in the field below. If you enter any other text in the field below, your report will be ignored.

[log.txt](https://github.com/get-iplayer/get_iplayer/files/13426976/log.txt)

### If you are using the Web PVR, provide your web browser name and version. This information typically can be found from the application menu via Chrome/Firefox/Safari->About... (macOS) or Help->About... (Linux/Windows)

N/A

**Comment by notnac** [comment]
As a workaround for now, don't use non-ASCII characters in the value of `--tag-only-filename`, which means you'll need to move the file or use a symbolic link to the directory.
